apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-account.yaml
- roles.yaml
- service.yaml
- consumer.yaml
- route.yaml
- secret.yaml
- hw-event-proxy.yaml
replicas:
- count: 1
  name: cloud-native-consumer-deployment
- count: 1
  name: hw-event-proxy
images:
- name: cloud-event-proxy
  newName: quay.io/redhat_emp1/cloud-event-proxy
  newTag: latest
- name: cloud-native-event-consumer
  newName: quay.io/redhat_emp1/cloud-native-event-consumer
  newTag: latest
- name: hw-event-proxy
  newName: quay.io/redhat_emp1/hw-event-proxy
  newTag: latest
