apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-consumer-sa
  namespace: cloud-native-events
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hw-event-proxy-sa
  namespace: cloud-native-events
