# Example consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      serviceAccountName: sidecar-consumer-sa
      containers:
        - name: cloud-event-consumer
          image: cloud-event-consumer
          args:
            - "--local-api-addr=localhost:9089"
            - "--api-path=/api/ocloudNotifications/v1/"
            - "--api-addr=localhost:8089"
            - "--http-event-publishers=hw-event-publisher-service.$(TRANSPORT_NAMESPACE).svc.cluster.local:$(TRANSPORT_PORT)"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TRANSPORT_NAMESPACE
              value: "openshift-bare-metal-events"
            - name: TRANSPORT_PORT
              value: "9043"
            - name: CONSUMER_TYPE
              value: "HW"
            - name: LOG_LEVEL
              value: "debug"
            - name: ENABLE_STATUS_CHECK
              value: "false"
        - name: cloud-event-sidecar
          image: cloud-event-sidecar
          args:
            - "--metrics-addr=127.0.0.1:9091"
            - "--store-path=/store"
            - "--transport-host=$(TRANSPORT_PROTOCAL)://$(TRANSPORT_SERVICE).$(TRANSPORT_NAMESPACE).svc.cluster.local:$(TRANSPORT_PORT)"
            - "--http-event-publishers=hw-event-publisher-service.$(TRANSPORT_NAMESPACE).svc.cluster.local:$(TRANSPORT_PORT)"
            - "--api-port=8089"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TRANSPORT_PROTOCAL
              value: "http"
            - name: TRANSPORT_SERVICE
              value: "consumer-events-subscription-service"
            - name: TRANSPORT_NAMESPACE
              value: "openshift-bare-metal-events"
            - name: TRANSPORT_PORT
              value: "9043"
            - name: LOG_LEVEL
              value: "debug"
          volumeMounts:
            - name: pubsubstore
              mountPath: /store
          ports:
            - name: metrics-port
              containerPort: 9091
        - name: kube-rbac-proxy
          image: quay.io/coreos/kube-rbac-proxy:v0.5.0
          args:
            - --logtostderr
            - --secure-listen-address=:8443
            - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
            - --upstream=http://127.0.0.1:9091/
            - --tls-private-key-file=/etc/metrics/tls.key
            - --tls-cert-file=/etc/metrics/tls.crt
          ports:
            - containerPort: 8443
              name: https
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: sidecar-certs
              mountPath: /etc/metrics
      volumes:
        - name: pubsubstore
          emptyDir: {}
        - name: sidecar-certs
          secret:
            secretName: sidecar-consumer-secret
